# OpenAI Configuration for MailoBot CALM

# API Configuration
api:
  endpoint: https://api.openai.com/v1
  # Use environment variable for API key
  api_key_env: OPENAI_API_KEY
  organization_env: OPENAI_ORGANIZATION_ID  # Optional

# Model Configuration
models:
  # Default model for general usage
  default: gpt-3.5-turbo
  # Specific models for different tasks
  rephraser: gpt-3.5-turbo
  summarizer: gpt-3.5-turbo
  draft_generator: gpt-4
  analyzer: gpt-3.5-turbo

# Request Parameters
parameters:
  rephraser:
    temperature: 0.3
    max_tokens: 50
    top_p: 0.9
    frequency_penalty: 0.0
    presence_penalty: 0.0
  
  # Other task-specific parameters
  summarizer:
    temperature: 0.5
    max_tokens: 200
  
  draft_generator:
    temperature: 0.7
    max_tokens: 500
  
  analyzer:
    temperature: 0.2
    max_tokens: 300

# System Prompts for different flows
prompts:
  email_management: >
    You are an AI email management assistant. Your task is to interpret user queries about
    email organization, filtering, marking, and deletion. Rephrase the user's message to match
    the most appropriate email management intent.

  email_drafting: >
    You are an AI email drafting assistant. Your task is to interpret user requests for
    writing, editing, saving, or sending emails. Rephrase the user's message to match
    the most appropriate email drafting intent.

  email_search: >
    You are an AI email search assistant. Your task is to interpret user queries about
    finding specific emails by sender, subject, date, content, or attachments. Rephrase
    the user's message to match the most appropriate email search intent.

  read_email: >
    You are an AI email reading assistant. Your task is to interpret user requests for
    reading, replying to, forwarding, or deleting specific emails. Rephrase the user's
    message to match the most appropriate email reading intent.

  main_flow: >
    You are an AI email assistant. Your task is to interpret general user queries about
    emails and email management. Rephrase the user's message to match the most appropriate
    email-related intent.
